# Generated by Django 2.2.11 on 2022-06-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_product_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='digital',
        ),
    ]
