# Generated by Django 2.2.11 on 2022-06-17 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20220608_1845'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='isNew',
            field=models.BooleanField(null=True),
        ),
    ]
